### ISSUE TITLE
Facebook comment area not rendering

### ISSUE THREAD

**Issue by Creator2010** [webtechnick/CakePHP-Facebook-Plugin#17]
i have tested echo $this->Facebook->share(); to know if the plugin was working,this worked without errors.i tried using echo $facebook->comments(); but the comment area is not showing.

I have included echo $this->Facebook->html()  and $this->Facebook->init(); in the default layout. Its not displaying any error,neither is displaying the facebook comment.

I then changed the facebook plugin parameters to a wrong one. The echo $this->Facebook->share() still worked.what could be wrong.

<?php
/**
- Get an api_key and secret from facebook and fill in this content.
- save the file to app/config/facebook.php
  */
  $config = array(
  'Facebookx' => array(
  'appId' => '',
  'apiKey' => '',
  'secret' => '',
  
    'cookie' => true,
    'locale' => 'en_US',
  )
  );
  ?>
  what could be wrong

**Comment by bigzee** [comment]
Is this issue not going to get any love. I have seen multiple people having the same problem and it all leads to the same place, a dead end. I seen a similar issue closed, is it really closed when someone needs to modify the script and hard code something that should work dynamically, meaning there didn't seem to be any resolve to the issue. I have posted on few different boards concerning this issue and have not received one response. If you don't know the reason, that's fine, I'm ok with that, just tell us, don't leave questions and concerns hanging out there with nothing. If your trying to figure it out, cool too, just communicate that.  I see the potential of this plugin and it would fit all my needs. I just wish you'd address it rather than seemingly pretending it doesn't exist. Or if there is a solution that has been put out there kindly redirect people to that solution as I have not been able to find it over my last two days of browsing and posting.

**Comment by wildleaf** [comment]
$facebook->comments(array('migrated'=> '1'));

**Comment by bigzee** [comment]
Thx wildleaf, but that's a big negative. Tried that one. It's everything but the share that isn't working... You can see an example of what it's doing on one of my article pages, this one for example... http://2ndrevolt.com/articles/article_view/212 The way it's currently setup, the comments should be below the share, not their final spot, but good for testing and comparison. If you firebug it you'll see that the tag is there, yet greyed out, meaning it's considered unrendered...?

Again thx, but anymore ideas...

**Comment by webtechnick** [comment]
It appears you have an extra x in your 'Facebookx' configuration, is that just a typo or did you copy/paste your configuration file?  You'll need to remove that.  Comments are tested and working in the demo application.  Is this still an issue?  If so, please provide me some more information.  What version of CakePHP are you running? What server are you running etc... What version of the plugin are you using?

**Comment by webtechnick** [comment]
Closing for lack of feedback.
