### ISSUE TITLE
save same user for every hit

### ISSUE THREAD

**Issue by milinaudara** [webtechnick/CakePHP-Facebook-Plugin#83]
I am using cakephp 2.2 and this plugn but it save the loged user every time(every hit)
and logout button do not display

**Comment by webtechnick** [comment]
Make sure your facebook_id is a bigint(22) in your database, otherwise it gets saved as the INT(11) cap which isn't the actual facebook_id.  As such the plugin can't find the facebook_id in your database (since its the int cap) and tries to create another one, to which your database turns the bigint into the int resulting in the same issue.

**Comment by milinaudara** [comment]
Thank u very much. This plugin is awesome
